[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "Lilex Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Lilex Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Lilex Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Lilex Nerd Font Mono"
style = "Regular"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.9
startup_mode = "Maximized"

[window.padding]
x = 10
y = 0
